### ISSUE TITLE
ENKI E-puck local communications using modulated infrareds 

### ISSUE THREAD

**Issue by david1309** [enki-community/enki#11]
Hello, is there the **_librlcom**_ library implemented in the functionality of the E-puck model in ENKI. If yes, how can one make use of it.

If i isn't implemented, does any body know how to adapt the model so that it enables this functionality ?

**Comment by stephanemagnenat** [comment]
As we talked live, I suggest to implement a LocalInteraction providing this feature.

**Comment by david1309** [comment]
Yes, I will try to modify enki source code to implement the local interaction ... thanks for the advice
