### ISSUE TITLE
Build for Python3x and add support for Thymio2 in pyenki

### ISSUE THREAD

**Issue by titos-carrasco** [enki-community/enki#67]
Here is a fix to compile/build for python3 and add support for Thymio2 in pyenki: [rcr-enki.patch.zip](https://github.com/enki-community/enki/files/6473176/rcr-enki.patch.zip)

    roberto@debian:~/.../enki$  git apply rcr-enki.patch
or

    C:\...>  git apply rcr-enki.patch

**Linux**

    roberto@debian:~/.../enki$ cmake -DCMAKE_BUILD_TYPE=Release -DOpenGL_GL_PREFERENCE=GLVND .

**Windows (with Visual Studio Tools 2019, boost 1.7.6  and Qt5)**

Build Boos 1.7.6

    C:\...> bootstrap.bat vc142
    C:\...> b2 --clean
    C:\...> b2 --build . --with-python --prefix=C:\Users\titos\Documents\Software\boost176 ^
            address-model=64 variant=release link=shared threading=multi runtime-link=shared install

Build Enki

    C:\...> cmake ^
            -DQt5_DIR=C:\Qt\Qt5.12.10\5.12.10\msvc2017_64\lib\cmake\Qt5 ^
            -DBoost_INCLUDE_DIR=C:\Users\titos\Documents\Software\boost176\include\boost-1_76 ^
            -DBoost_LIBRARY_DIR_RELEASE=C:\Users\titos\Documents\Software\boost176\lib ^
            -DBoost_PYTHON39_LIBRARY_RELEASE=C:\Users\titos\Documents\Software\boost176\lib\boost_python39-vc142-mt-x64-1_76.lib .
    C:\...> cmake --build . --config Release

I use this structure of directories

![image](https://user-images.githubusercontent.com/4842986/118153314-c17bdb80-b3e3-11eb-9b22-67a8ab8a487f.png)

**Comment by stephanemagnenat** [comment]
Your patch would break Python2 support, right? In the robotics world, due to hardware support, distribution constraints and research reproducibility, some people are still using Python2. I'll be glad to add support for Python3, but would like to not break Python2 for now.

**Comment by titos-carrasco** [comment]
Please omit this patch so it affect python2 users
