### ISSUE TITLE
pyenki does not show Thymio2 robot

### ISSUE THREAD

**Issue by titos-carrasco** [enki-community/enki#69]
![image](https://user-images.githubusercontent.com/4842986/118644432-c9ed6100-b7ab-11eb-88d7-f29fb8441d10.png)

Apply patch in  [pyenki-thymio2.patch.zip](https://github.com/enki-community/enki/files/6501003/pyenki-thymio2.patch.zip)

![image](https://user-images.githubusercontent.com/4842986/118644748-205a9f80-b7ac-11eb-9b26-c4b7846c9a29.png)

**Comment by stephanemagnenat** [comment]
Thank you for spotting the issue and providing a correction.
