### ISSUE TITLE
No support for LEDs in EPuck/Thymio2 robots in pyenki

### ISSUE THREAD

**Issue by titos-carrasco** [enki-community/enki#70]
Apply this patch to support LEDs in EPuck and Thymio2 robots inside pyenki [rcr-pyenki-leds.patch.zip](https://github.com/enki-community/enki/files/6504358/rcr-pyenki-leds.patch.zip)

![image](https://user-images.githubusercontent.com/4842986/118721620-1ad77680-b7f9-11eb-9ed5-6cefe78482f5.png) ![image](https://user-images.githubusercontent.com/4842986/118721656-2460de80-b7f9-11eb-9a6c-b1b8ba890eb2.png)

**Comment by stephanemagnenat** [comment]
Thank you for the patch, I've applied a simplified version of it, as the wrapper methods for `setLedIntensity` and `setLedColor` were not needed due to the implicit cast of int to enum in C++.

**Comment by titos-carrasco** [comment]
But without the function wrapper I got

> Thymio2.setLedIntensity(MyThymio2, int, bool)
> did not match C++ signature:
> setLedIntensity(Enki::Thymio2 {lvalue}, Enki::Thymio2::LedIndex, double)

**Comment by stephanemagnenat** [comment]
You mean, at execution? If so, why do you pass a bool to as the last parameter of led intensity and not a number between 0 and 1?

**Comment by titos-carrasco** [comment]
It works with 0/1 and True/False without problem with the wrapper

**Comment by stephanemagnenat** [comment]
Sure, but a boolean is not an intensity. We could add a function with another name, e.g. calling it `setLedOnOff`.

**Comment by titos-carrasco** [comment]
There was an error in my test code. Fixed, but now

>    e.setLedIntensity( 0, 1.0 )
>Boost.Python.ArgumentError: Python argument types in
>    Thymio2.setLedIntensity(MyRobot, int, float)
>did not match C++ signature:
>    setLedIntensity(Enki::Thymio2 {lvalue}, Enki::Thymio2::LedIndex, double)

**Comment by stephanemagnenat** [comment]
I guess `MyRobot` inherits from `Enki::Thymio2` in Python, right?

Interesting, I am wondering whether the problem is with the LedIndex or with the float vs double. I would guess the former. If so, I can of course add the methods you have in your patch.

**Comment by titos-carrasco** [comment]
The problem is qith the cast of LedIndex ... tested

**Comment by stephanemagnenat** [comment]
Ok, then I'll use your functions.

**Comment by titos-carrasco** [comment]
Thanks for your software. 

I will use it for education. Look at [pyPlayground](https://github.com/titos-carrasco/pyplayground)

**Comment by stephanemagnenat** [comment]
Functions added in f1fcf67.
